In [24]:
#loading the library
import pandas as pd

df = pd.read_excel("../data/final_pricing_dataset.xlsx",header =0)

In [25]:
df = df.drop("month", axis=1)

df["demand"] = df["demand"] + (df["temperature"] - 25) * 2
df["demand"] = df["demand"].clip(lower=0)

In [26]:
####### DATA CLEANING #######
df["date"] = pd.to_datetime(df["date"]).dt.date

In [27]:
df["profit"] = (df["price"] - df["cost"]) * df["demand"]

In [28]:
#Checking the dataset using head
df.head(10)

,date,product,price,cost,demand,temperature,is_weekend,is_festival,promo,competitor_price,day_of_week,profit
0,2010-12-01,WHITE HANGING HEART T-LIGHT HOLDER,2.55,1.530,8.1,26.05,0,0,0,1.55,Wednesday,8.2620
1,2010-12-01,WHITE METAL LANTERN,3.39,2.034,14.1,29.05,0,0,0,1.00,Wednesday,19.1196
2,2010-12-01,CREAM CUPID HEARTS COAT HANGER,2.75,1.650,4.1,23.05,0,0,0,0.75,Wednesday,4.5100
3,2010-12-01,KNITTED UNION FLAG HOT WATER BOTTLE,3.39,2.034,2.1,23.05,0,1,1,2.39,Wednesday,2.8476
4,2010-12-01,RED WOOLLY HOTTIE WHITE HEART.,3.39,2.034,2.1,23.05,0,0,1,5.39,Wednesday,2.8476
5,2010-12-01,SET 7 BABUSHKA NESTING BOXES,7.65,4.590,8.1,28.05,0,0,1,5.65,Wednesday,24.7860
6,2010-12-01,GLASS STAR FROSTED T-LIGHT HOLDER,4.25,2.550,0.1,22.05,0,0,0,6.25,Wednesday,0.1700
7,2010-12-01,HAND WARMER UNION JACK,1.85,1.110,4.1,24.05,0,0,1,2.85,Wednesday,3.0340
8,2010-12-01,HAND WARMER RED POLKA DOT,1.85,1.110,0.1,22.05,0,0,1,1.00,Wednesday,0.0740
9,2010-12-01,ASSORTED COLOUR BIRD ORNAMENT,1.69,1.014,42.1,30.05,0,0,1,3.69,Wednesday,28.4596

In [29]:
df.shape

(19999, 12)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              19999 non-null  object
 1   product           19999 non-null  str
 2   price             19999 non-null  float64
 3   cost              19999 non-null  float64
 4   demand            19999 non-null  float64
 5   temperature       19999 non-null  float64
 6   is_weekend        19999 non-null  int64
 7   is_festival       19999 non-null  int64
 8   promo             19999 non-null  int64
 9   competitor_price  19999 non-null  float64
 10  day_of_week       19999 non-null  str
 11  profit            19999 non-null  float64
dtypes: float64(6), int64(3), object(1), str(2)
memory usage: 1.8+ MB

In [31]:
df.columns

Index(['date', 'product', 'price', 'cost', 'demand', 'temperature',
       'is_weekend', 'is_festival', 'promo', 'competitor_price', 'day_of_week',
       'profit'],
      dtype='str')

In [32]:
df.describe()

,price,cost,demand,temperature,is_weekend,is_festival,promo,competitor_price,profit
count,19999.000000,19999.000000,19999.000000,19999.00000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000
mean,4.930849,2.958509,9.943152,25.04295,0.135407,0.101455,0.498975,4.143881,11.862158
std,97.864251,58.718551,41.305024,3.15639,0.342166,0.301938,0.500011,97.788543,130.265689
min,0.070000,0.042000,0.000000,20.05000,0.000000,0.000000,0.000000,-1.880000,0.000000
25%,1.450000,0.870000,0.000000,22.05000,0.000000,0.000000,0.000000,0.510000,0.000000
50%,2.510000,1.506000,5.100000,25.05000,0.000000,0.000000,0.000000,2.210000,4.026000
75%,4.250000,2.550000,11.100000,28.05000,0.000000,0.000000,1.000000,4.350000,11.050000
max,13541.330000,8124.798000,2880.100000,30.05000,1.000000,1.000000,1.000000,13539.330000,16791.249200

In [33]:
import plotly.express as px

In [36]:
# DEMAND DISTRIBUTION

fig = px.histogram(df[df["demand"] < 100],
                x="demand",
                nbins=50,
                title="Demand Distribution (Filtered)",
                color_discrete_sequence=["#636EFA"])

fig.show()

In [37]:
# PRICE VS DEMAND 

fig = px.scatter((df[(df["price"]< 50) & (df["demand"] < 100)]),
                x="price",
                y="demand",
                color="demand",
                title="Price vs Demand",
                color_continuous_scale="viridis")

fig.show()

In [38]:
# PROMO VS DEMAND
promo_df = df.groupby("promo")["demand"].mean().reset_index()

fig = px.bar(promo_df,
            x="promo",
            y="demand",
            color="promo",
            title="Promo vs Demand",
            color_discrete_sequence=["#EF553B", "#00CC96"])

fig.show()

In [39]:
#PROFIT DISTRIBUTION

fig = px.histogram(df[df["profit"]< 30],
                x="profit",
                nbins=50,
                title="Profit Distribution",
                color_discrete_sequence=["#AB63FA"])

fig.show()

In [40]:
# TEMPERATURE VS DEMAND

fig = px.scatter(df,
                x="temperature",
                y="demand",
                color="temperature",
                title="Temperature vs Demand",
                color_continuous_scale="plasma")

fig.show()

In [41]:
#WEEKEND VS DEMAND
week_df = df.groupby("is_weekend")["demand"].mean().reset_index()

fig = px.bar(week_df,
            x="is_weekend",
            y="demand",
            color="is_weekend",
            title="Weekend vs Demand",
            color_discrete_sequence=["#FFA15A", "#19D3F3"])

fig.show()

In [42]:
#correlation heatmap

import plotly.figure_factory as ff

corr = df.select_dtypes(include="number").corr()

fig = px.imshow(
    corr,
    text_auto=True,
    aspect="auto",
    color_continuous_scale="viridis",
    title="Correlation Heatmap"
)

fig.update_layout(
    width=800,
    height=700
)

fig.show()